#!/bin/bash
#
# "ldconfig" wrapper for scratchbox 2:
# ldconfig is a statically linked binary.
#
# Copyright (c) 2008 Nokia Corporation.
# All rights reserved.
# Author: Lauri T. Aarnio
#
# Licensed under GPL version 2

args="$*"
prog="$0"
progbase=`basename $0`

function error_not_inside_lb()
{
	echo "ldbox: $progbase wrapper: This wrapper can only be used from inside"
	echo "the scratchbox 2'ed environment"
	exit 1
}

if [ -z "$LDBOX_SESSION_DIR" ]
then
	error_not_inside_lb
fi

. $LDBOX_SESSION_DIR/lb-session.conf

if [ -z "$ldbox_mapmode" -o -z "$ldbox_dir" ]
then
	error_not_inside_lb
fi

ldbox_ldconfig_path=""
ldbox_ldconfig_root=""
# read-in mode-specific settings
if [ -f $LDBOX_SESSION_DIR/modes/$ldbox_mapmode/lbrc ]
then
	. $LDBOX_SESSION_DIR/modes/$ldbox_mapmode/lbrc "$progbase"
fi

if [ -z "$ldbox_ldconfig_path" ]
then
	ldbox_ldconfig_path="$ldbox_target_root/sbin/ldconfig"
fi
if [ -z "$ldbox_ldconfig_root" ]
then
	ldbox_ldconfig_root="$ldbox_target_root"
fi

export LDBOX_ALLOW_STATIC_BINARY=$ldbox_ldconfig_path
exec $ldbox_ldconfig_path -r "$ldbox_ldconfig_root" $args
